/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Matheus
 */
public class ViewMenuPrincipal extends javax.swing.JFrame {

     private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = jDesktopPane.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }
     
    public ViewMenuPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jDesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiCadastroAdm = new javax.swing.JMenuItem();
        jmiCadastrarAlunos = new javax.swing.JMenuItem();
        jmiCadastrarCardapio = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiConsulta = new javax.swing.JMenuItem();
        jmiConsultarAlunos = new javax.swing.JMenuItem();
        jmiConsultarCardapio = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setText("Tecno Food");

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(510, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );

        jDesktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPaneLayout.createSequentialGroup()
                .addGap(0, 365, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Cadastros");
        jMenu1.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N

        jmiCadastroAdm.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jmiCadastroAdm.setText("Cadastrar Administrador");
        jmiCadastroAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastroAdmActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCadastroAdm);

        jmiCadastrarAlunos.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jmiCadastrarAlunos.setText("Cadastrar Alunos");
        jmiCadastrarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarAlunosActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCadastrarAlunos);

        jmiCadastrarCardapio.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jmiCadastrarCardapio.setText("Cadastrar Cardapio Mensal");
        jmiCadastrarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadastrarCardapioActionPerformed(evt);
            }
        });
        jMenu1.add(jmiCadastrarCardapio);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");
        jMenu2.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N

        jmiConsulta.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jmiConsulta.setText("Consultar administradores");
        jmiConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiConsulta);

        jmiConsultarAlunos.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jmiConsultarAlunos.setText("Consultar alunos");
        jmiConsultarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarAlunosActionPerformed(evt);
            }
        });
        jMenu2.add(jmiConsultarAlunos);

        jmiConsultarCardapio.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jmiConsultarCardapio.setText("Consultar cardápio");
        jmiConsultarCardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarCardapioActionPerformed(evt);
            }
        });
        jMenu2.add(jmiConsultarCardapio);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatórios");
        jMenu3.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jmiCadastroAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastroAdmActionPerformed
        ViewCadastroAdm cadAdm = new ViewCadastroAdm();
        jDesktopPane.add(cadAdm);
        centralizaForm(cadAdm);
        cadAdm.setVisible(true);
    }//GEN-LAST:event_jmiCadastroAdmActionPerformed

    private void jmiConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaActionPerformed
        ViewCRUDAdm crudAdm = new ViewCRUDAdm();
        jDesktopPane.add(crudAdm);
        centralizaForm(crudAdm);
        crudAdm.setVisible(true);
    }//GEN-LAST:event_jmiConsultaActionPerformed

    private void jmiCadastrarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarAlunosActionPerformed
        ViewCadastroAluno cadAluno = new ViewCadastroAluno();
        jDesktopPane.add(cadAluno);
        centralizaForm(cadAluno);
        cadAluno.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarAlunosActionPerformed

    private void jmiConsultarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarAlunosActionPerformed
        ViewCRUDAluno crudAluno = new ViewCRUDAluno();
        jDesktopPane.add(crudAluno);
        centralizaForm(crudAluno);
        crudAluno.setVisible(true);
    }//GEN-LAST:event_jmiConsultarAlunosActionPerformed

    private void jmiCadastrarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadastrarCardapioActionPerformed
        ViewCadastroCardapio cadCardapio = new ViewCadastroCardapio();
        jDesktopPane.add(cadCardapio);
        centralizaForm(cadCardapio);
        cadCardapio.setVisible(true);
    }//GEN-LAST:event_jmiCadastrarCardapioActionPerformed

    private void jmiConsultarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarCardapioActionPerformed
        ViewCRUDCardapio crudCardapio = new ViewCRUDCardapio();
        jDesktopPane.add(crudCardapio);
        centralizaForm(crudCardapio);
        crudCardapio.setVisible(true);
    }//GEN-LAST:event_jmiConsultarCardapioActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem jmiCadastrarAlunos;
    private javax.swing.JMenuItem jmiCadastrarCardapio;
    private javax.swing.JMenuItem jmiCadastroAdm;
    private javax.swing.JMenuItem jmiConsulta;
    private javax.swing.JMenuItem jmiConsultarAlunos;
    private javax.swing.JMenuItem jmiConsultarCardapio;
    // End of variables declaration//GEN-END:variables
}
